apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  type: NodePort
  selector:
    app: nginx-multitool
  ports:
    - name: nginx-port
      port: 9001
      targetPort: 80
      nodePort: 30080
    - name: multitool-port
      port: 9002
      targetPort: 8080