---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static

vector: "vector"
vector_version: "0.24.1"
vector_base_url: https://packages.timber.io/vector/