apiVersion: v1
kind: Pod
metadata:
  name: nginx-init
  labels:
    app: nginx-init
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
  initContainers:
    - name: init-myservice
      image: busybox
      command: ['nslookup', 'nginx-svc.default.svc.cluster.local']