apiVersion: v1
kind: Service
metadata:
  name: nginx-multitool-svc
spec:
  selector:
    app: nginx-multitool
  ports:
    - name: nginx-port
      port: 80
      targetPort: 80
    - name: multitool-port
      port: 8080
      targetPort: 1180