{
 "title": "Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "CPU Load Time %",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)  ",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "CPU Load average Queue",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPU_LA1" },
    { "expr": "node_load5", "legendFormat": "CPU_LA5" },
    { "expr": "node_load15", "legendFormat": "CPU_LA15" }
   ]
  },
  {
   "title": "File System Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs\"}*100  ",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "node_memory_Inactive_bytes/node_memory_MemAvailable_bytes*100  ",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}